name: abey_wallet
description: A new Flutter application.
publish_to: 'none'

version: 3.1.3+313

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.18.0
  firebase_analytics: ^9.1.10
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^11.4.2
  firebase_messaging_platform_interface: ^3.5.2
  flustars: ^2.0.1
  fluttertoast: ^8.0.6
  flutter_easyloading: ^3.0.0
  flutter_easyrefresh: ^2.2.1
  flutter_local_notifications: ^12.0.2
  connectivity_plus: ^2.0.3
  crypto: ^3.0.1
  decimal: ^1.3.0
  dio: ^4.0.6
  event_bus: ^2.0.0
  extended_nested_scroll_view: ^5.0.0
  package_info: ^2.0.2
  sqflite: ^2.0.2
  shared_preferences: ^2.0.12
  share_extend: ^2.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  permission_handler: ^9.0.2
  qr_flutter: ^4.0.0
  logger: ^1.0.0
  url_launcher: ^6.0.13
  sticky_headers: ^0.2.0
  cached_network_image: ^3.1.1
  local_auth: ^2.1.0
  pointycastle: ^3.0.1

  flutter_card_swipper: ^0.4.0
  convert: ^3.0.1
  device_info: ^2.0.0
  encrypt: ^5.0.1
  fluintl: ^0.1.3
  syncfusion_flutter_pdfviewer: ^19.3.48-beta
  ansicolor: ^2.0.0-nullsafety.0

  bee_encryption:
    path: plugins/bee_encryption
  abey_encryption:
    path: plugins/abey_encryption
  get:
    path: plugins/getx
  r_scan:
    path: plugins/r_scan
  webview_flutter:
    path: plugins/webview_flutter-2.0.12
  webview_flutter_plus:
    path: plugins/webview_flutter_plus-0.2.2

#  web3dart:
#    path: plugins/web3dart

#  pointycastle: ^3.6.2
  sec: ^1.0.1
  http: ^0.13.5
  uuid: ^3.0.7
  json_rpc_2: ^3.0.2
  stream_transform: ^2.1.0
  stream_channel: ^2.1.1
  eip55: ^1.0.2
  eip1559: ^0.6.0
  typed_data: ^1.3.1
#  convert: ^3.1.1
  async: ^2.10.0
  wallet: ^0.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/files/
    - assets/images/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf